### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by PeterTihanyi** [Vlad-Herus/CollapseRegionExtension#1]
Thank you Vladimir, this is exactly the extension I was about to research how to create on my own, as I was unable to get through anybody with this in the VS team and other solutions are either bad, bloated or discontinued. Your solution works perfectly, I have no complaints. :)

To make this an issue with something to fix, I'll mention that you made a typo in the extension's description in the marketplace, but I don't really mind that. All I wanted to say was thank you, as this is the only way I can message you.

"Collapse/Expand #reions in code window." <-- Typo.

**Comment by Vlad-Herus** [comment]
cheers. fixed.
