### ISSUE TITLE
Could you add the option to collapse XAML Regions?

### ISSUE THREAD

**Issue by PrimaForge** [Vlad-Herus/CollapseRegionExtension#2]
I downloaded this extension hoping It would work for XAML since I do alot of WPF work. I did some testing and It seems it does not. I was wondering if you could add support for XAML also?

**Comment by ygoe** [comment]
You can find more information about the XAML region syntax here: https://stackoverflow.com/questions/2888347/region-in-xaml

**Comment by Vlad-Herus** [comment]
@FutureTD @ygoe @AppyxDaniel [new version is out](https://marketplace.visualstudio.com/items?itemName=VladH.CollapseRegionExtension) 

@Vert-by, thanks for the PR
